### ISSUE TITLE
Nielsen Reconciliation Service

### ISSUE THREAD

**Issue by fgarcia44** [fgarcia44/lakitu-expansion#27]
### Business Tracker: [GOTTP-13383 Nielsen Reconciliation Service](https://wiki.at.sky/display/OVP/GOTTP-13383+AGF+Nielsen+Phase+2+-+Data+Completion+Microservice)

# Description

The new component is not a microservice as other OVP components. Instead it's a group of AWS services setup to provide Nielsen with the required metadata for the content.

- APIx to provide the metadata needed to link VOD content with its Linear equivalent.
- APIx to push mapping of asset to the linear channel as JSON document (see "Low-Level Design" below).
- Lambda to validate JSON "schema" and push payload to S3 bucket
  - Needs to rewrite incoming URL to include a key prefix
- CloudFront to "front" S3 bucket
  - CloudFront function to rewrite incoming URL to include a key prefix
- Devices come via CloudFront to read mapping files

# Reference documentation
- [Neilsen Microservice](https://wiki.at.sky/display/GRPD/Neilsen+Microservice)
- [Nielsen reconciliation service](https://wiki.at.sky/display/~gbn15/Nielsen+reconciliation+service)
- [GOTTP-13383 - AGF Nielsen Audience Measurement](https://wiki.at.sky/display/~ORU02/GOTTP-13383+-+AGF+Nielsen+Audience+Measurement)
- [Nielsen Reconciliation API](https://wiki.at.sky/display/~ORU02/Nielsen+Reconciliation+API)

# Development Plan
### Spikes/Investigations
- [ ] Using S3 buckets

### MVP
- [ ] writing test phases
- [ ] unit tests for functionality
- [ ] extended FTs
- [ ] integration tests (S3, APIGW)
- [ ] NFTs
- [ ] application level metrics (ie failed to save to S3, not matching contentId pattern...)
- [ ] ServiceCi creation

### Non-MVP
- [ ]
