### ISSUE TITLE
Swap order of Territory and Provider in Video config for DRM HDCP Fields

### ISSUE THREAD

**Issue by fgarcia44** [fgarcia44/lakitu-expansion#3]
# Background

As part of the migration to enable wildcarding in the video config for multiple territories in one provider all the Provider/Territory configuration needs to be standardised so that the order in the config is in Provider>Territory.

For the DRM fields for Widevine HDCP and FairPlay HDCP the order is Territory>Provider:

For the DRM fields for Widevine HDCP:

        "widevine": {
          "defaultLevel": "HDCP_V1",
          "byTerritoryAndProvider": {
            "US": {
              "NBCU": {
                "MOBILE": {
                  "ANDROID": "HDCP_NONE"
                },
                "TABLET": {
                  "ANDROID": "HDCP_NONE"
                }
              }
            }
          }
        },

For the DRM fields for FairPlay:

         "fairPlay": {
          "defaultLevel": "1",
          "byTerritoryAndProvider": {}
        }

# Requirement

The config in Video for Widevine HDCP needs to change so that the order is Provider>Territory:

        "widevine": {
          "defaultLevel": "HDCP_V1",
          "byProviderAndTerritory": {                   
            "NBCU": {                        <<<----- This has swapped
              "US": {                          <<<-----  This has swapped
                "MOBILE": {
                  "ANDROID": "HDCP_NONE"
                },
                "TABLET": {
                  "ANDROID": "HDCP_NONE"
                }
              }
            }
          }
        },

The config in Video needs to change for FairPlay so that the order is Provider>Territory:

        "fairPlay": {
          "defaultLevel": "1",
          "byProviderAndTerritory": {}   <<<---  This is the order that needs to be changed
        }

# Implementation

# Tasks
 - [x] Get the prod config reviewed and push
 - [x] Demo the changes
# Defuzz:
- [x] Swap order for all protection types in the drm block.
